Repository yhtang/FunFact, pull requests merged in 2022-01, with the labels that each got.

#129 Initializers
  docs/api/initializers.md
  funfact/__init__.py
  funfact/backend/_jax.py
  funfact/backend/_numpy.py
  funfact/backend/_torch.py
  funfact/backend/test_backend.py
  funfact/initializers.py
  funfact/lang/interpreter/_initialization.py
  funfact/lang/interpreter/test_einop.py
  funfact/test_initializers.py
  mkdocs.yml
Labels: priority

#134 Vectorization of `kron` and `matmul` nodes.
  funfact/lang/interpreter/_vectorize.py
Labels: bug

#145 Conditions and preferences for penalties on loss function
  funfact/__init__.py
  funfact/algorithm.py
  funfact/backend/_jax.py
  funfact/backend/_torch.py
  funfact/conditions.py
  funfact/initializers.py
  funfact/lang/_terminal.py
  funfact/lang/_tsrex.py
  funfact/lang/interpreter/__init__.py
  funfact/lang/interpreter/_initialization.py
  funfact/model/_factorization.py
  funfact/test_conditions.py
Labels: feature

#150 Fix bug when populating tensors from concrete initializers
  funfact/lang/interpreter/_initialization.py
  funfact/lang/interpreter/test_initialization.py
Labels: bug

#153 Fix `initializers.stack` bug when classes are given as the initializer of tensors
  funfact/initializers.py
Labels: bug

#165 Update the CFG docs page.
  docs/pages/user-guide/cfg.md
  docs/pages/user-guide/tensor-and-indices.md
  mkdocs.yml
Labels: documentation

#168 Add cheatsheet page of documentation. Closes #167.
  docs/javascripts/tablesort.js
  docs/pages/cheatsheet.md
  docs/pages/user-guide/tensor-and-indices.md
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: documentation

#170 Readme and documentation home page update
  README.md
  docs/index.md
  docs/pycuda/__init__.py
  mkdocs.yml
Labels: documentation

#171 quantum notebook. Closes #99
  docs/examples/nn_circuit.png
  docs/examples/qft_circuit.png
  docs/examples/quantum-compilation.ipynb
  mkdocs.yml
Labels: documentation

#172 Documentation for tensor and index creations. Closes #112.
  docs/api/eye.md
  docs/api/index_.md
  docs/api/ones.md
  docs/api/zeros.md
  docs/pages/user-guide/tensor-and-indices.md
  docs/pages/user-guide/tsrex.md
  mkdocs.yml
Labels: documentation

#174 Use tabs for better clarity in showing installation commands
  docs/pages/installation.md
Labels: documentation

#180 Refactored einop. Closes #109
  funfact/lang/interpreter/_einop.py
Labels: feature

#185 Precompile einop specifications using live indices. Fixes #182.
  funfact/lang/_tsrex.py
  funfact/lang/interpreter/__init__.py
  funfact/lang/interpreter/_einop.py
  funfact/lang/interpreter/_einop_compiler.py
  funfact/lang/interpreter/_einspec.py
  funfact/lang/interpreter/_elementwise.py
  funfact/lang/interpreter/_evaluation.py
  funfact/lang/interpreter/_type_deduction.py
  funfact/lang/interpreter/test_einop.py
  funfact/model/_factorization.py
  funfact/vectorization.py
Labels: bug
